//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppAKonsult.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using GruppAKonsult.ViewModels;

    public partial class CV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CV()
        {
            this.Profession = new HashSet<Profession>();
        }

        public IEnumerable<SelectListItem> AllProfessions { get; set; }
        public List<int> listOfProfessions;
        public List<int> ListOfProfessions;


        public int CV_Id { get; set; }
        public int Candidate_Id { get; set; }
        public string Drivinglicense { get; set; }
        public string Description { get; set; }
        public string Education { get; set; }
        public string Workexperience { get; set; }
    
        public virtual Freelancer Freelancer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Profession> Profession { get; set; }
    }
}
