//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppAKonsult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public int CV_Id { get; set; }
        public int Candidate_Id { get; set; }
        public string Swedish { get; set; }
        public string English { get; set; }
        public string French { get; set; }
        public string Spanish { get; set; }
        public string German { get; set; }
        public string Norwegian { get; set; }
        public string Danish { get; set; }
        public string Finnish { get; set; }
    
        public virtual Freelancer Freelancer { get; set; }
    }
}
