//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppAKonsult.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GruppAKonsult_dbEntities2 : DbContext
    {
        public GruppAKonsult_dbEntities2()
            : base("name=GruppAKonsult_dbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CV> CV { get; set; }
        public virtual DbSet<Employer> Employer { get; set; }
        public virtual DbSet<Freelancer> Freelancer { get; set; }
        public virtual DbSet<Jobbank> Jobbank { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Profession> Profession { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
    }
}
