//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppAKonsult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int Profile_Id { get; set; }
        public int Employer_Id { get; set; }
        public int Candidate_Id { get; set; }
    
        public virtual Employer Employer { get; set; }
        public virtual Freelancer Freelancer { get; set; }
    }
}
