//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GruppAKonsult.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profession
    {
        public int Candidate_Id { get; set; }
        public int CV_Id { get; set; }
        public string Webbdeveloper { get; set; }
        public string Systemdeveloper { get; set; }
        public string Programmer { get; set; }
        public string Softwareengineer { get; set; }
        public string Frontenddeveloper { get; set; }
        public string Backenddeveloper { get; set; }
        public string Javadeveloper { get; set; }
        public string Scrummaster { get; set; }
    
        public virtual CV CV { get; set; }
    }
}
